In [1]:
!pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (2.0.1)
Requirement already satisfied: bleach in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.17 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (0.1.18)
Requirement already satisfied: packaging in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (26.1)
Requirement already satisfied: protobuf in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (7.34.1)
Requirement already satisfied: python-dateutil in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.33.1)
Requirement already satisfied: tqdm in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (2026.2.25)
Requirement already satisfied: colorama in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from tqdm->kaggle) (0.4.6)

In [ ]:
#import libraries
import kaggle

In [3]:
import sys
!"{sys.executable}" -m pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (2.0.1)
Requirement already satisfied: bleach in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.17 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (0.1.18)
Requirement already satisfied: packaging in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (26.1)
Requirement already satisfied: protobuf in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (7.34.1)
Requirement already satisfied: python-dateutil in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.33.1)
Requirement already satisfied: tqdm in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from kaggle) (2.6.3)
Requirement already satisfied: webencodings in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from requests->kaggle) (2026.2.25)
Requirement already satisfied: colorama in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from tqdm->kaggle) (0.4.6)

In [4]:
print(sys.version)

3.14.4 (tags/v3.14.4:23116f9, Apr  7 2026, 14:10:54) [MSC v.1944 64 bit (AMD64)]

In [5]:
!kaggle datasets download ankitbansal06/retail-orders

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading retail-orders.zip to c:\Users\Shristi singh\Desktop\my_codes\Python_code

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|██████████| 200k/200k [00:00<00:00, 254kB/s]
100%|██████████| 200k/200k [00:00<00:00, 253kB/s]

In [1]:
#downloaded version is a zip file and i want to extract data from there
#using zip library to achieve above

import zipfile

my_ref = zipfile.ZipFile('retail-orders.zip')

In [2]:
my_ref.extractall() #extract file to dir
my_ref.close() #close file

In [3]:
#read the data from the file and handle null values
import pandas as pd

df = pd.read_csv('orders.csv')

In [4]:
!pip install  pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Shristi singh\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 1.7 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.9 MB 2.2 MB/s eta 0:00:05
   ------ --------------------------------- 1.6/9.9 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.9 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.9 MB 2.3 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.9 MB 2.3 MB/s eta 0:00:03
   --------------- ------------------------ 3.9/9.9 MB 2.5 MB/s eta 0:00:03
   --------------- ------------------------ 3.9/9.9 MB 2.5 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.9 MB 2.2 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.9 MB 2.0 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.9 MB 2.0 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.9 MB 1.8 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.9 MB 1.8 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.9 MB 1.8 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.9 MB 1.7 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.9 MB 1.7 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.9 MB 1.5 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.9 MB 1.5 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.9 MB 1.5 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.9 MB 1.5 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.9 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.3 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.9 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.9 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.9 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.9 MB 1.1 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.9 MB 1.1 MB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 924.5 kB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 924.5 kB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 924.5 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 885.3 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 885.3 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 872.0 kB/s eta 0:00:04
   ---------------------------- ----------- 7.1/9.9 MB 873.7 kB/s eta 0:00:04
   ---------------------------- ----------- 7.1/9.9 MB 873.7 kB/s eta 0:00:04
   ----------------------------- ---------- 7.3/9.9 MB 878.4 kB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 875.8 kB/s eta 0:00:03
   ------------------------------- -------- 7.9/9.9 MB 881.2 kB/s eta 0:00:03
   ------------------------------- -------- 7.9/9.9 MB 881.2 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.9 MB 897.4 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 907.9 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 924.3 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 924.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 912.7 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 915.5 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 926.0 kB/s  0:00:10
Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 1.8 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/12.4 MB 1.5 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/12.4 MB 1.5 MB/s eta 0:00:08
   ----- ---------------------------------- 1.6/12.4 MB 1.6 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/12.4 MB 1.5 MB/s eta 0:00:08
   ------- -------------------------------- 2.4/12.4 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.4 MB 1.7 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.4 MB 1.7 MB/s eta 0:00:06
   ---------- ----------------------------- 3.4/12.4 MB 1.7 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.4 MB 1.7 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.4 MB 1.7 MB/s eta 0:00:05
   --------------- ------------------------ 4.7/12.4 MB 1.8 MB/s eta 0:00:05
   ---------------- ----------------------- 5.0/12.4 MB 1.8 MB/s eta 0:00:05
   ----------------- ---------------------- 5.5/12.4 MB 1.8 MB/s eta 0:00:04
   ------------------- -------------------- 6.0/12.4 MB 1.9 MB/s eta 0:00:04
   --------------------- ------------------ 6.6/12.4 MB 1.9 MB/s eta 0:00:04
   ---------------------- ----------------- 7.1/12.4 MB 2.0 MB/s eta 0:00:03
   ------------------------- -------------- 7.9/12.4 MB 2.0 MB/s eta 0:00:03
   --------------------------- ------------ 8.7/12.4 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.4 MB 2.2 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 2.3 MB/s  0:00:05
Downloading tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

In [21]:
import pandas as pd
#both zip file and csv files were present in same path that is why given only file's name not the whole path
df = pd.read_csv('orders.csv')

In [4]:
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,Not Available,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,Not Available,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,Not Available,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,unknown,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [5]:
#there are some 'not available', 'unknown' , 'None'"#Python code.py"
#we want to consider them as null

#to get distinct values available in a particular column
df['Ship Mode'].unique()

<StringArray>
[  'Second Class', 'Standard Class',  'Not Available',        'unknown',
    'First Class',              nan,       'Same Day']
Length: 7, dtype: str

In [6]:
# na_values -> treats particular value as null (converts)
df = pd.read_csv('orders.csv',na_values = ['Not Available','unknown'])

In [7]:
df['Ship Mode'].unique()

<StringArray>
['Second Class', 'Standard Class', nan, 'First Class', 'Same Day']
Length: 5, dtype: str

In [8]:
 #rename column names..make them lower case and replace space with underscore

df.rename(columns = {'Order Id':'order_id', 'City':'city','Order Date': 'order_date','Postal Code':'postal_code'})

,order_id,order_date,Ship Mode,Segment,Country,city,State,postal_code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [9]:
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='str')

In [10]:
#can't pick cols one by one and change it, so use below method
df.columns = df.columns.str.lower()

In [11]:
df.columns =df.columns.str.replace(' ','_')

In [12]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [13]:
#derive new columns discount, sale price and profit
df['discount'] = df['list_price']*df['discount_percent']*.01

In [14]:
df['discount'].head()

0     5.2
1    21.9
2     0.5
3    19.2
4     1.0
Name: discount, dtype: float64

In [15]:
df['sale_price'] = df['list_price'] - df['discount']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8

In [16]:
df['profit'] = df['sale_price'] - df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [17]:
#convert order date from object data type to datetime -> it should go as a date not as string into database
#if it wont go as a date, we'll not be able to perform all the operations.
df.dtypes

order_id              int64
order_date              str
ship_mode               str
segment                 str
country                 str
city                    str
state                   str
postal_code           int64
region                  str
category                str
sub_category            str
product_id              str
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [18]:
df['order_date'] = pd.to_datetime(df['order_date'],format ="%Y-%m-%d")

In [19]:
#drop cost price , list price  and discount percent columns - not required for analysis anymore
df.drop(columns=['list_price','cost_price','discount_percent'],inplace = True)

In [44]:
!pip install sqlalchemy psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.49-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 1.3 MB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.1 MB 1.4 MB/s eta 0:00:01
   ------------------- -------------------- 1.0/2.1 MB 1.4 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 1.6 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.5 MB/s  0:00:01
Downloading psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 797.7 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.8 MB 820.7 kB/s eta 0:00:03
   -------------- ------------------------- 1.0/2.8 MB 990.0 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 1.2 MB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.8 MB 1.3 MB/s eta 0:00:01
   ----------------------------- ---------- 2.1/2.8 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 2.6/2.8 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 1.4 MB/s  0:00:01
Downloading greenlet-3.4.0-cp314-cp314-win_amd64.whl (239 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, psycopg2-binary, greenlet, sqlalchemy

   ---------- ----------------------------- 1/4 [psycopg2-binary]
   ---------- ----------------------------- 1/4 [psycopg2-binary]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ---------------------------------------- 4/4 [sqlalchemy]

Successfully installed greenlet-3.4.0 psycopg2-binary-2.9.11 sqlalchemy-2.0.49 typing-extensions-4.15.0

In [20]:
#drop data into posgres
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:1234@localhost:5432/postgres")
conn = engine.connect()

print("Connected!")

Connected!

In [24]:
df.to_sql('df_orders',con=conn ,index =False, if_exists = 'append')

994